name: flutter_model_assert
description: "Early runtime validator for backend JSON responses to prevent type crashes and detect API contract mismatches in Flutter."
version: 0.0.5
homepage: https://github.com/battalasiva/flutter_model_assert
repository: https://github.com/battalasiva/flutter_model_assert

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.2.0
  build_runner: ^2.4.8
flutter:
